alias go="sudo /home/russell/sh/go.sh"
alias wpa="sudo /home/russell/sh/wpa.sh"
alias apa="sudo /etc/init.d/apache2 restart"
alias sc="/home/russell/sh/sc.sh"
alias win="sudo mount.ntfs-fuse /dev/sda2 /media/windows"
alias woot="banner woot"
alias mob="sudo pkill xmobar && xmobar &"
