alias lol="echo 'you are so funny!'"
alias bleh="echo 'bummer..'"
alias wpa="sudo /home/millertime/sh/wpa.sh"
alias off="sudo poweroff"
alias irc="ssh-add && ssh screen"
alias env="source ENV/bin/activate"
